<a href="https://colab.research.google.com/github/SARA3SAEED/more-practice/blob/main/DA_Mu_Lab9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [8]:
ar0= np.zeros(10)
ar0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr =np.array([0,0,0,0,0,0,0,0,0,0])
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [9]:
ar1= np.ones(10)
ar1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
arr1=np.array([1,1,1,1,1,1,1,1,1,1])
arr1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [10]:
ar2 = np.ones(10)*5
ar2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [11]:
ar3= np.full(10, 5)
ar3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [4]:
arr2 = np.array([5,5,5,5,5,5,5,5,5,5])
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [5]:
arr3 = np.arange(10,51)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
arr4 = np.arange(10,51,2)
arr4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
arr5 = np.arange(0,9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [12]:
arr6 = np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [13]:
arr7 = np.random.rand(1)
arr7

array([0.77538258])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [14]:
arr8 = np.random.randn(25)
arr8

array([-7.19861931e-01,  3.38227755e-01,  5.83269225e-01, -4.53159365e-01,
        4.81436130e-01, -3.27530279e-01,  8.36582211e-01, -1.40668737e-03,
       -6.14510530e-01, -7.22303981e-01, -3.49008708e-01,  4.93006307e-02,
        2.41613534e-01, -5.94313294e-01, -1.62338393e+00,  2.09099443e+00,
        7.64561623e-01, -1.28462807e+00, -5.53228331e-01, -1.25323530e+00,
        6.31031581e-01,  7.74385477e-01, -2.54591635e-01,  9.76014958e-01,
       -6.79839964e-01])

#### Create the following matrix:

In [15]:
arr9 = np.arange(0.01,1.01,0.01).reshape(10,10)
arr9

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [16]:
arr10 = np.linspace(0,1,20)
arr10

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Numpy Indexing and Selection, write code that reproduces the output of the cell below

In [17]:
arr11 = np.arange(1,26).reshape(5,5)
arr11

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
arr11[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
arr11[3,4]

20

In [21]:
arr11[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [24]:
arr11[4:,]

array([[21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [25]:
arr11.sum()

325

#### Get the standard deviation of the values in mat

In [27]:
arr11.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [28]:
arr11.sum(axis=0) #col

array([55, 60, 65, 70, 75])

In [29]:
arr11.sum(axis=1) #row

array([ 15,  40,  65,  90, 115])

==========

# Great Job!